version: 2

sources:
  - name: raw
    schema: ZELDA_DBT   # ou ton dataset BigQuery
    tables:
      - name: games
      - name: platforms
      - name: game_platform
      - name: sales
      - name: reviews